package jp.ahoashi.guitarchord.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val monoLightScheme = lightColorScheme(
    primary = Color(0xFF2C2C2C),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFDEDEDE),
    onPrimaryContainer = Color(0xFF111111),
    secondary = Color(0xFF555555),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFEAEAEA),
    onSecondaryContainer = Color(0xFF1C1C1C),
    tertiary = Color(0xFF6B6B6B),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFF0F0F0),
    onTertiaryContainer = Color(0xFF1C1C1C),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    background = Color(0xFFF8F8F8),
    onBackground = Color(0xFF1A1A1A),
    surface = Color(0xFFF8F8F8),
    onSurface = Color(0xFF1A1A1A),
    surfaceVariant = Color(0xFFE4E4E4),
    onSurfaceVariant = Color(0xFF444444),
    outline = Color(0xFF909090),
    outlineVariant = Color(0xFFCCCCCC),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF2C2C2C),
    inverseOnSurface = Color(0xFFF4F4F4),
    inversePrimary = Color(0xFFBBBBBB),
    surfaceDim = Color(0xFFDEDEDE),
    surfaceBright = Color(0xFFF8F8F8),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF3F3F3),
    surfaceContainer = Color(0xFFEEEEEE),
    surfaceContainerHigh = Color(0xFFE8E8E8),
    surfaceContainerHighest = Color(0xFFE2E2E2),
)

val monoDarkScheme = darkColorScheme(
    primary = Color(0xFFD4D4D4),
    onPrimary = Color(0xFF1A1A1A),
    primaryContainer = Color(0xFF3A3A3A),
    onPrimaryContainer = Color(0xFFEEEEEE),
    secondary = Color(0xFFB0B0B0),
    onSecondary = Color(0xFF242424),
    secondaryContainer = Color(0xFF3A3A3A),
    onSecondaryContainer = Color(0xFFEAEAEA),
    tertiary = Color(0xFF909090),
    onTertiary = Color(0xFF181818),
    tertiaryContainer = Color(0xFF3A3A3A),
    onTertiaryContainer = Color(0xFFD4D4D4),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF111111),
    onBackground = Color(0xFFE0E0E0),
    surface = Color(0xFF111111),
    onSurface = Color(0xFFE0E0E0),
    surfaceVariant = Color(0xFF2E2E2E),
    onSurfaceVariant = Color(0xFFBBBBBB),
    outline = Color(0xFF707070),
    outlineVariant = Color(0xFF3A3A3A),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFE0E0E0),
    inverseOnSurface = Color(0xFF2C2C2C),
    inversePrimary = Color(0xFF3A3A3A),
    surfaceDim = Color(0xFF111111),
    surfaceBright = Color(0xFF363636),
    surfaceContainerLowest = Color(0xFF080808),
    surfaceContainerLow = Color(0xFF1A1A1A),
    surfaceContainer = Color(0xFF1E1E1E),
    surfaceContainerHigh = Color(0xFF282828),
    surfaceContainerHighest = Color(0xFF323232),
)
