package jp.ahoashi.guitarchord.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val yellowLightScheme = lightColorScheme(
    primary = Color(0xFF7A6E3A),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFF5E8A0),
    onPrimaryContainer = Color(0xFF241E00),
    secondary = Color(0xFF786A42),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFF4E4B8),
    onSecondaryContainer = Color(0xFF261E04),
    tertiary = Color(0xFF4E7060),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFCCEADC),
    onTertiaryContainer = Color(0xFF082218),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    background = Color(0xFFFDFCEE),
    onBackground = Color(0xFF1E1C14),
    surface = Color(0xFFFDFCEE),
    onSurface = Color(0xFF1E1C14),
    surfaceVariant = Color(0xFFEAE4CC),
    onSurfaceVariant = Color(0xFF4A4638),
    outline = Color(0xFF7C7862),
    outlineVariant = Color(0xFFCECAB0),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF333128),
    inverseOnSurface = Color(0xFFF6F4E4),
    inversePrimary = Color(0xFFD8CA7A),
    surfaceDim = Color(0xFFDFDCCC),
    surfaceBright = Color(0xFFFDFCEE),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF7F5E6),
    surfaceContainer = Color(0xFFF2F0E0),
    surfaceContainerHigh = Color(0xFFECEADA),
    surfaceContainerHighest = Color(0xFFE7E5D5),
)

val yellowDarkScheme = darkColorScheme(
    primary = Color(0xFFD8CA7A),
    onPrimary = Color(0xFF3D380A),
    primaryContainer = Color(0xFF5A5220),
    onPrimaryContainer = Color(0xFFF5E8A0),
    secondary = Color(0xFFD8C490),
    onSecondary = Color(0xFF3E3414),
    secondaryContainer = Color(0xFF584C28),
    onSecondaryContainer = Color(0xFFF4E4B8),
    tertiary = Color(0xFFB0CCBE),
    onTertiary = Color(0xFF1A3C2E),
    tertiaryContainer = Color(0xFF345646),
    onTertiaryContainer = Color(0xFFCCEADC),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF1E1C14),
    onBackground = Color(0xFFE7E5D5),
    surface = Color(0xFF1E1C14),
    onSurface = Color(0xFFE7E5D5),
    surfaceVariant = Color(0xFF4A4638),
    onSurfaceVariant = Color(0xFFCECAB0),
    outline = Color(0xFF98937E),
    outlineVariant = Color(0xFF4A4638),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFE7E5D5),
    inverseOnSurface = Color(0xFF333128),
    inversePrimary = Color(0xFF7A6E3A),
    surfaceDim = Color(0xFF1E1C14),
    surfaceBright = Color(0xFF3A382E),
    surfaceContainerLowest = Color(0xFF18160E),
    surfaceContainerLow = Color(0xFF221E18),
    surfaceContainer = Color(0xFF27241C),
    surfaceContainerHigh = Color(0xFF312E26),
    surfaceContainerHighest = Color(0xFF3C3A30),
)
