package jp.ahoashi.guitarchord.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val blueLightScheme = lightColorScheme(
    primary = Color(0xFF5B6B9E),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFDDE1FF),
    onPrimaryContainer = Color(0xFF101B42),
    secondary = Color(0xFF5C6478),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFDFE2FF),
    onSecondaryContainer = Color(0xFF181E32),
    tertiary = Color(0xFF5C5E8C),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFE2DEFF),
    onTertiaryContainer = Color(0xFF18183A),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    background = Color(0xFFF8F8FF),
    onBackground = Color(0xFF1A1C22),
    surface = Color(0xFFF8F8FF),
    onSurface = Color(0xFF1A1C22),
    surfaceVariant = Color(0xFFE0E1EE),
    onSurfaceVariant = Color(0xFF44464F),
    outline = Color(0xFF757680),
    outlineVariant = Color(0xFFC5C5D2),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF2F3038),
    inverseOnSurface = Color(0xFFF1F0F9),
    inversePrimary = Color(0xFFBAC3F5),
    surfaceDim = Color(0xFFD9D9E8),
    surfaceBright = Color(0xFFF8F8FF),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF2F2FA),
    surfaceContainer = Color(0xFFECECF5),
    surfaceContainerHigh = Color(0xFFE6E7EF),
    surfaceContainerHighest = Color(0xFFE1E1EA),
)

val blueDarkScheme = darkColorScheme(
    primary = Color(0xFFBAC3F5),
    onPrimary = Color(0xFF253060),
    primaryContainer = Color(0xFF3E4E80),
    onPrimaryContainer = Color(0xFFDDE1FF),
    secondary = Color(0xFFBFC5DC),
    onSecondary = Color(0xFF2A3048),
    secondaryContainer = Color(0xFF424A60),
    onSecondaryContainer = Color(0xFFDFE2FF),
    tertiary = Color(0xFFC4C2F5),
    onTertiary = Color(0xFF2C2D58),
    tertiaryContainer = Color(0xFF444572),
    onTertiaryContainer = Color(0xFFE2DEFF),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF1A1C22),
    onBackground = Color(0xFFE1E1EA),
    surface = Color(0xFF1A1C22),
    onSurface = Color(0xFFE1E1EA),
    surfaceVariant = Color(0xFF44464F),
    onSurfaceVariant = Color(0xFFC5C5D2),
    outline = Color(0xFF8F909B),
    outlineVariant = Color(0xFF44464F),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFE1E1EA),
    inverseOnSurface = Color(0xFF2F3038),
    inversePrimary = Color(0xFF5B6B9E),
    surfaceDim = Color(0xFF1A1C22),
    surfaceBright = Color(0xFF383A48),
    surfaceContainerLowest = Color(0xFF14161C),
    surfaceContainerLow = Color(0xFF1E2028),
    surfaceContainer = Color(0xFF22242C),
    surfaceContainerHigh = Color(0xFF2D2F38),
    surfaceContainerHighest = Color(0xFF383A44),
)
