package jp.ahoashi.guitarchord.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val greenLightScheme = lightColorScheme(
    primary = Color(0xFF5A7A62),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFC8EDD0),
    onPrimaryContainer = Color(0xFF0C2214),
    secondary = Color(0xFF5A7060),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFCAE8D2),
    onSecondaryContainer = Color(0xFF122018),
    tertiary = Color(0xFF3A7070),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFBCEAE8),
    onTertiaryContainer = Color(0xFF002222),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    background = Color(0xFFF5FBF5),
    onBackground = Color(0xFF181C18),
    surface = Color(0xFFF5FBF5),
    onSurface = Color(0xFF181C18),
    surfaceVariant = Color(0xFFD8E8DC),
    onSurfaceVariant = Color(0xFF3E4840),
    outline = Color(0xFF6E786F),
    outlineVariant = Color(0xFFBECCC0),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF2C312D),
    inverseOnSurface = Color(0xFFEDF3ED),
    inversePrimary = Color(0xFFAAD4B2),
    surfaceDim = Color(0xFFD4DAD5),
    surfaceBright = Color(0xFFF5FBF5),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFEFF5EF),
    surfaceContainer = Color(0xFFE9EFE9),
    surfaceContainerHigh = Color(0xFFE3E9E4),
    surfaceContainerHighest = Color(0xFFDDE4DE),
)

val greenDarkScheme = darkColorScheme(
    primary = Color(0xFFAAD4B2),
    onPrimary = Color(0xFF1E4428),
    primaryContainer = Color(0xFF385E40),
    onPrimaryContainer = Color(0xFFC8EDD0),
    secondary = Color(0xFFAACCB4),
    onSecondary = Color(0xFF1E3C28),
    secondaryContainer = Color(0xFF38543E),
    onSecondaryContainer = Color(0xFFCAE8D2),
    tertiary = Color(0xFFA0CCCA),
    onTertiary = Color(0xFF003C3C),
    tertiaryContainer = Color(0xFF1E5454),
    onTertiaryContainer = Color(0xFFBCEAE8),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF181C18),
    onBackground = Color(0xFFDDE4DE),
    surface = Color(0xFF181C18),
    onSurface = Color(0xFFDDE4DE),
    surfaceVariant = Color(0xFF3E4840),
    onSurfaceVariant = Color(0xFFBECCC0),
    outline = Color(0xFF889189),
    outlineVariant = Color(0xFF3E4840),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFDDE4DE),
    inverseOnSurface = Color(0xFF2C312D),
    inversePrimary = Color(0xFF5A7A62),
    surfaceDim = Color(0xFF181C18),
    surfaceBright = Color(0xFF343A34),
    surfaceContainerLowest = Color(0xFF121612),
    surfaceContainerLow = Color(0xFF1C201C),
    surfaceContainer = Color(0xFF202420),
    surfaceContainerHigh = Color(0xFF2A302A),
    surfaceContainerHighest = Color(0xFF353B35),
)
