package jp.ahoashi.guitarchord.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val redLightScheme = lightColorScheme(
    primary = Color(0xFF8B5E6A),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFD8E1),
    onPrimaryContainer = Color(0xFF3A1020),
    secondary = Color(0xFF7A5E63),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFD8DE),
    onSecondaryContainer = Color(0xFF311020),
    tertiary = Color(0xFF7A5E3A),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFDEB8),
    onTertiaryContainer = Color(0xFF2E1800),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    background = Color(0xFFFFF8F8),
    onBackground = Color(0xFF221A1C),
    surface = Color(0xFFFFF8F8),
    onSurface = Color(0xFF221A1C),
    surfaceVariant = Color(0xFFF2DDE1),
    onSurfaceVariant = Color(0xFF514347),
    outline = Color(0xFF847377),
    outlineVariant = Color(0xFFD6C2C5),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF382E30),
    inverseOnSurface = Color(0xFFFDEEF0),
    inversePrimary = Color(0xFFE8B4C2),
    surfaceDim = Color(0xFFE8D5D8),
    surfaceBright = Color(0xFFFFF8F8),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFFF1F3),
    surfaceContainer = Color(0xFFFCEAED),
    surfaceContainerHigh = Color(0xFFF6E4E7),
    surfaceContainerHighest = Color(0xFFF0DEE1),
)

val redDarkScheme = darkColorScheme(
    primary = Color(0xFFE8B4C2),
    onPrimary = Color(0xFF4E2535),
    primaryContainer = Color(0xFF6B3F4C),
    onPrimaryContainer = Color(0xFFFFD8E1),
    secondary = Color(0xFFE8B4BA),
    onSecondary = Color(0xFF4A2530),
    secondaryContainer = Color(0xFF5F3840),
    onSecondaryContainer = Color(0xFFFFD8DE),
    tertiary = Color(0xFFE8C4A0),
    onTertiary = Color(0xFF45300F),
    tertiaryContainer = Color(0xFF5D4525),
    onTertiaryContainer = Color(0xFFFFDEB8),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF221A1C),
    onBackground = Color(0xFFF0DEE1),
    surface = Color(0xFF221A1C),
    onSurface = Color(0xFFF0DEE1),
    surfaceVariant = Color(0xFF514347),
    onSurfaceVariant = Color(0xFFD6C2C5),
    outline = Color(0xFF9E8C90),
    outlineVariant = Color(0xFF514347),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFF0DEE1),
    inverseOnSurface = Color(0xFF382E30),
    inversePrimary = Color(0xFF8B5E6A),
    surfaceDim = Color(0xFF221A1C),
    surfaceBright = Color(0xFF493840),
    surfaceContainerLowest = Color(0xFF1C1416),
    surfaceContainerLow = Color(0xFF2A2024),
    surfaceContainer = Color(0xFF2F2428),
    surfaceContainerHigh = Color(0xFF3A2E32),
    surfaceContainerHighest = Color(0xFF45383D),
)
